name: techpicks
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  http: ^1.1.0

  cupertino_icons: ^1.0.8
  video_player: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  animated_text_kit: ^4.2.1
  salomon_bottom_bar: ^3.3.2
  easy_localization: ^3.0.7
  restart_app: ^1.2.1
  device_info_plus: ^10.0.2
  webview_flutter: ^4.9.0
  permission_handler: ^10.2.0 # 권한 요청 패키지
  firebase_vertexai: ^0.2.3+4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/Video/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/logo/logo.png
  android: true
  ios: true
