name: techpicks
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  # json_serializable 6.14+ 가 ^3.8.0 이상을 요구한다.
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  easy_localization: ^3.0.7
  shared_preferences: ^2.5.5
  firebase_ai: ^3.15.0
  dio: ^5.11.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  flutter_riverpod: ^3.4.2
  device_info_plus: ^13.2.0
  animations: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.15.1
  freezed: ^3.0.0
  json_serializable: ^6.14.1
  riverpod: ^3.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/translations/
    - assets/catalog/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo2.png"

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/logo/logo.png
  android: true
  ios: true
